lib/Imagine/Test/Constraint/IsImageEqual.php

The signature of \Imagine\Test\Constraint\IsImageEqual::evaluate does not match the one in the parent class \PHPUnit_Framework_Constraint. In PHP5.5 this leads to a runtime notice.
This change fixes the signature.

Fix signature mismatch in IsImageEqual constraint

---

.travis.yml

The ``download/`` folder only contains the archive for the latest release, and so the URL becomes invalid each time a new release is done. Using permanent URLs for the download is better

Change the ImageMagick download URL

---

.travis.yml

This PR
:information_desk_person: Seems like the location has changed since the last PR (https://github.com/avalanche123/Imagine/pull/433) was merged.
See http://www.imagemagick.org/download/releases/.
/cc @romainneutron @stof

Fix: Download ImageMagick tar from appropriate location

---

lib/Imagine/Filter/Basic/Autorotate.php
tests/Imagine/Test/Filter/Basic/AutorotateTest.php

EXIF allows for eight orientations, four of which are currently
handled.  This adds functionality to handle the remaining four, which
have to be mirrored as well as rotated.

Handle all possible orientations when autorotating

---

.gitignore

This PR
:bulb: It shows up as untracked file when I install dependencies.

Fix: Add composer.lock to .gitignore

---

lib/Imagine/Image/Metadata/ExifMetadataReader.php

The stream's contents have probably already been read, thus the pointer is at the EOF already.
Rewinding the stream fixes this issue.

Fix for extracting EXIF metadata from stream

---

lib/Imagine/Gd/Imagine.php
lib/Imagine/Gmagick/Imagine.php
lib/Imagine/Image/ImageInterface.php
lib/Imagine/Image/Metadata/AbstractMetadataReader.php
lib/Imagine/Image/Metadata/ExifMetadataReader.php
lib/Imagine/Image/Metadata/MetadataReaderInterface.php
lib/Imagine/Imagick/Imagine.php
tests/Imagine/Test/Image/AbstractImagineTest.php

This is the correct fix for #454, we must not read stream more than once.

Fix #254 : Do not read stream more than once

---

lib/Imagine/Image/Metadata/ExifMetadataReader.php

exif_read_data can read from the filesystem just fine, so if we get an image path, doing file_get_contents() will load up the file in memory, and then passing it to doReadData will base64_encode it which typically adds 1/3rd of the binary size to the output, so you add 1.3x the image size into the memory. 
This is all fine with thumbnail sized images but when dealing with large files you very easily and unnecessarily blow up the memory limit.
There is no 0.6 branch but this applies cleanly on 0.6.3 as well, in case you'd like to do a new release :)

Avoid using 2.3x the image size worth of memory when no memory is enough

---

docs/usage/filters.rst

The simple present-tense verb "lets" should not carry an apostrophe in this case.

Remove Bad Apostrophe

---

lib/Imagine/Image/Box.php

This pull request provides an option to provide only $width when the Box is intended to be a square

If box is a square, providing width is enough

---

lib/Imagine/Gd/Image.php

I could not make GD\Image::applyMask() to work as described in Reflection example in http://www.slideshare.net/avalanche123/introduction-toimagine so I made some fixes.
1. It still supports only RGB palette for mask, but now accounts average between colors.
2. It does change image if its transparency is less than 0.5.

Getting applyMask to work

---

lib/Imagine/Imagick/Image.php

Looks like starting with imagemagick 6.8.8, you have to use `setCompressionQuality` instead of `setImageCompressionQuality`.

png compression method changed in imagemagick 6.8.8

---

docs/API/API/css/panel.css

Double slash for css comments should't be used.
See http://stackoverflow.com/questions/12298890/is-it-bad-practice-to-comment-out-single-lines-of-css-with

Double slash for css comment should't be used

---

lib/Imagine/Imagick/Image.php

See: http://php.net/manual/en/imagick.rotateimage.php#119455
> Some transformations including Imagick ::rotateImage() may change "image page" -- working area inside the image you work on.
Be careful with future modifications afterwards because the image page would be different from new sizes of the image.
For example, if you do Imagic::cropImage() after rotation, you need to set image page properly, otherwise your crop would be performed relating to wrong coordinates (depending on rotation angle, resulting image size may vary).

Fix Imagick 'rotate': reset canvas size after operation

---

lib/Imagine/Imagick/Image.php

Let's factorize Imagick version detection instead of adding a new parsing

Revert "png compression method changed in imagemagick 6.8.8"

---

lib/Imagine/Imagick/Imagine.php

This fixes a backwards compatibility issue introduced with
v3.4.3 of the php imagick extension. The method has been renamed to
setImageAlpha. See the imagick release notes for more info.
https://pecl.php.net/package-changelog.php?package=imagick&release=3.4.3
Fixes #539

Use setImageAlpha instead of deprecated setImageOpacity

---

composer.json

it's only needed when running tests

move PHPUnit Bridge to dev requirements

---

lib/Imagine/Gd/Image.php
lib/Imagine/Gmagick/Image.php
lib/Imagine/Imagick/Image.php

These lines are needed to support webp with the imagick adapter.
I don't intend to write webp support for the other adapters, but this may be a start for someone else.
Also requested in #271

Support webp 

---

lib/Imagine/Gmagick/Image.php

There are some image options that are only supported by some adapters and in the past these always got ignored.
With #504 a `NotSupportedException` was added for the `webp_lossless` option in the Gmagick adapter (but not the GD adapter). That was probably a mistake? If so, I think we should remove the exception.
/cc @chregu @alexander-schranz

Remove not-supported exception for image option

---

.gitattributes

What about removing this (big) PDF from autogenerated ZIP archives?
I don't think it's useful for production machines, developers that need this may still do a `git clone`.
Are the other PDF files needed for legal purposes or can we remove them too?

Remove unnecessary PDF from autogenerated ZIP archives

---

lib/Imagine/Gd/Image.php

Since PHP 5.5, GD implements the `imageflip` function: let's use it instead of copying pixels.

Use imageflip if available to flip a GD image

---

lib/Imagine/Image/Metadata/ExifMetadataReader.php

Instead of throwing exceptions
when exif_read_data fails, just
catch the exception and return
empty array.

Catch exif_read_data exceptions

---

lib/Imagine/Gmagick/Image.php

Function `\Imagine\Gmagick\Image::fill` browse some pixels outside of the image, due to a range error in `for` loop.
**Disclaimer:** Sorry, I didn't had time to write tests, I just wanted to point out this issue, and at least to propose a patch...

Fixed \Imagine\Gmagick\Image::fill

---

tests/bootstrap.php

Tests use relative paths to locate fixtures, and assume that the current working directory is the project root.

Set the current working directory for tests

---

tests/Imagine/Test/Image/AbstractImageTest.php

If a CMYK palette is reused (for instance because it's used in a Color instance cached in the `Palette\CMYK::$colors array`), the `testPaletteAssociatedIsRelatedToGivenColor` test may may because the reused palette instance may have a profile loaded, whereas the new palette instance may have a null profile.
So, let's always load the palette profile.

Force loading of palette profiles in testPaletteAssociatedIsRelatedToGivenColor

---

lib/Imagine/Gmagick/Image.php
lib/Imagine/Imagick/Image.php
tests/Imagine/Test/Gd/ImageTest.php
tests/Imagine/Test/Gmagick/ImageTest.php
tests/Imagine/Test/Image/AbstractImageTest.php
tests/Imagine/Test/Imagick/ImageTest.php

It is currently not possible to specify the sampling factors when saving a JPEG image. This pull request adds the option `jpeg_sampling_factors` to make that possible.

Add jpeg_sampling_factors option

---

docs/usage/introduction.rst

The basic introduction said to use alpha 100, but it should be using alpha 0 for transparent. I also added a second example with a solid color.

Fix incorrect alpha instructions for setting (background) colors

---

lib/Imagine/Imagick/Image.php

The C constant `MagickCore::TrueColorMatteType` was renamed to `MagickCore::TrueColorAlphaType` in ImageMagick version 7.0.1, see [ImageMagick@def23e5](https://github.com/ImageMagick/ImageMagick/commit/def23e5d7331b1a13ed593b6d6aca516da382328). This change was added as `Imagick::IMGTYPE_TRUECOLORALPHA` in PHP Imagick 3.4.3, see [Imagick@87ed96d](https://github.com/mkoppanen/imagick/commit/87ed96d7998aa5fa6c6e14ac54167c410153da9e).
I think we should use the new `IMGTYPE_...ALPHA` constants because the `IMGTYPE_...MATTE` constants are deprecated.

Use the Imagick::IMGTYPE_...ALPHA constants if available

---

CHANGELOG.md
lib/Imagine/Gmagick/Imagine.php

Typo fixed in GMagick\Imagine::create()

---

lib/Imagine/Image/AbstractImagine.php
lib/Imagine/Image/ImagineInterface.php

I know this is a BC break: people having a custom ImagineInterface implementation will have to update their classes. So I'm really open to discuss this.
PS: fix #487

Add MetadataReader getter/setter to ImagineInterface

---

CHANGELOG.md
lib/Imagine/Filter/Basic/Paste.php
lib/Imagine/Filter/Transformation.php
lib/Imagine/Gd/Image.php
lib/Imagine/Gd/Imagine.php
lib/Imagine/Gmagick/Image.php
lib/Imagine/Image/ManipulatorInterface.php
lib/Imagine/Imagick/Image.php
tests/Imagine/Test/Gmagick/ImageTest.php
tests/Imagine/Test/Image/AbstractImageTest.php

This supersedes #215
Tests for GD will probably fail, because of a bug in `Imagine\Gd\Imagine::create()`: I'll update this PR once tests are done.

Add opacity parameter to paste methods

---

tests/Imagine/Test/Image/AbstractImagineTest.php

I can't really get past what seems to me a bug of TravisCI:
```
gnutls_handshake() failed: A TLS packet with unexpected length was received.
```

Skip testShouldOpenAnHttpImage if curl+tls fails for a TravisCI (?) bug

---

lib/Imagine/Image/Box.php

Don't throw an exception when scaling a box too much

---

tests/Imagine/Test/Image/Metadata/MetadataReaderTestCase.php

I can't really get past what seems to me a bug of TravisCI:
```
gnutls_handshake() failed: A TLS packet with unexpected length was received.
```
See also #640 and #643

Skip testReadFromHttpFile if curl+tls fails for a TravisCI (?) bug

---

.appveyor.yml
.travis.yml
tests/Imagine/Test/Gd/ImageTest.php
tests/Imagine/Test/Gd/LayersTest.php
tests/Imagine/Test/Gmagick/ClassFactoryTest.php
tests/Imagine/Test/Gmagick/ImageTest.php
tests/Imagine/Test/Gmagick/ImagineTest.php
tests/Imagine/Test/Gmagick/LayersTest.php
tests/Imagine/Test/Image/AbstractImageTest.php
tests/Imagine/Test/Image/Palette/CMYKTest.php
tests/Imagine/Test/Image/Palette/Color/CMYKTest.php
tests/Imagine/Test/Imagick/ClassFactoryTest.php
tests/Imagine/Test/Imagick/ImageTest.php

Let's keep the phpunit output as clean as possible, to highlight actual stuff we should take care of.

Don't execute tests that will always be skipped

---

.php_cs.dist
.travis.yml
composer.json

Sample usage:
```bash
composer codestyle -- path/to/file.php
```

Allow using "codestyle" composer command to fix coding style

---

CHANGELOG.md
src/Image/Palette/Color/CMYK.php
src/Image/Palette/Color/ColorInterface.php
src/Image/Palette/Color/Gray.php
src/Image/Palette/Color/RGB.php

Every ColorInterface implementation already implements it, so by adding this we are sure it's available even in custom ColorInterface implementations.

Add __toString to ColorInterface

---

.gitignore
CHANGELOG.md
src/Imagick/Image.php
tests/Imagine/Test/Imagick/ImageTest.php
tests/bootstrap.php

Imagick can optimize animated GIF files, ~provided that the frames have the same size~.
Supersedes #252
EDIT: calling `coalesceImages` allows using `optimizeimagelayers` even if the frames have different sizes.

New imagick save option: optimize

---

tests/Imagine/Test/Image/Metadata/ExifMetadataReaderTest.php

I can't really get past what seems to me a bug of TravisCI:
```
gnutls_handshake() failed: A TLS packet with unexpected length was received.
```
See also #643

Skip testExifDataAreReadWithReadData if curl+tls fails for a TravisCI (?) bug

---

tests/Imagine/Test/Constraint/IsColorSimilar.php
tests/Imagine/Test/Constraint/IsColorSimilarTest.php
tests/Imagine/Test/ImagineTestCase.php

This can be useful to check if two colors are very near in tests.
It's not currently used, but it'd be fine to have it available for future tests.

Add IsColorSimilar constraint

---

src/Gmagick/Image.php

This is already done by Gmagick\Image::setColorspace()

Avoid assigning palette in Gmagick\Image::usePalette

---

tests/Imagine/Test/Image/Metadata/ExifMetadataReaderTest.php

I can't really get past what seems to me a bug of TravisCI:
```
gnutls_handshake() failed: A TLS packet with unexpected length was received.
```
See also #643

Skip testExifDataAreReadWithReadHttpFile if curl+tls fails for a TravisCI (?) bug

---

src/Gd/Drawer.php

The `imageantialias` is generally available after PHP 7.2.0. For versions before that, this check is needed.

Fix undefined method error with older PHP versions

---

composer.json
src/Image/Metadata/ExifMetadataReader.php

Reading the file data into memory is not needed for local files. This reduces memory consumption in ExifMetadataReader.

Read Exif data from local files directly

---

.travis.yml
.travis/imagick.sh
composer.json
src/Gd/Drawer.php
src/Gd/Effects.php
src/Gd/Image.php
src/Gd/Imagine.php
src/Gd/Layers.php
tests/tests/Filter/Advanced/BlackWhiteTest.php
tests/tests/Filter/Advanced/NeighborhoodTest.php

In PHP 8.0 the GD resources got replaced with `GdImage` objects, see https://github.com/php/php-src/commit/8aad466c42b5feabc7565856eb006c326f35382f

Fix compatibility with PHP 8.0

---

src/Imagick/Image.php
tests/tests/Image/AbstractImageTest.php

This is a followup pull request to #712 (#709)
I included @lashus commit from the original PR in 2a8e9e637ee137eb692beb10adb16d25ea1b89cd

Fix IMagick rotation canvas size

---

src/Gmagick/Image.php

Fixes #732 as discussed in https://github.com/avalanche123/Imagine/pull/747#issuecomment-721372830

Use uppercase format string to prevent no encode delegate error

---

src/Gd/Drawer.php
src/Gd/Layers.php
src/Gmagick/Layers.php
src/Image/Histogram/Bucket.php
src/Image/Metadata/MetadataBag.php
src/Imagick/Layers.php

Fixes the PHP 8.1 deprecations of:
1. https://wiki.php.net/rfc/internal_method_return_types
2. https://wiki.php.net/rfc/deprecations_php_8_1#num_points_parameter_of_image_open_filled_polygon
We should probably wait with merging this until an RC version of PHP 8.1 was released.

Fix PHP 8.1 deprecations

---

src/Gmagick/Effects.php
tests/tests/Gmagick/EffectsTest.php

1) Try-catch in Imagine\Gmagick\Effects::convolve should catch GmagickException instead of ImagickException.
2) Changed the case of the Gmagick methods calls to lowercase to match their declarations.
3) Imagine\Test\Gmagick\EffectsTest::testColorize now expects more specific NotSupportedException instead of rather common RuntimeException.
Main reason of this pull-request is 1), it is small bugfix.
I know that tests wanted, but I'm not sure that it is required in such case because looks like its copy-paste mistake.
I tested code using the following test:
in \Imagine\Test\Gmagick\EffectsTest add
```php
public function testConvolutionFailed()
{
$image = $this->getImagine()->create(new \Imagine\Image\Box(1, 1));
$matrix = new \Imagine\Utils\Matrix(3, 3, array(
0, 0.5, 0,
0.5, 1, 0.5,
0, 0.5, …
```

Try-catch in Imagine\Gmagick\Effects::convolve should catch GmagickException instead of ImagickException

---

src/Gd/Imagine.php
src/Gmagick/Imagine.php
src/Imagick/Imagine.php

Hello,
When coupled with `liip/imagine-bundle`, these classes can be set as lazy in symfony since they aren't necessary until resolving is needed.

remove final from drivers

---

src/Gd/Image.php
src/Gmagick/Image.php
src/Image/AbstractImage.php
src/Imagick/Image.php

Make the $filter parameter of the resize method invariant

---

src/Gmagick/DriverInfo.php
src/Imagick/DriverInfo.php

With the 1.3.0 release, an error now occured when using the Imagick or GMagick driver.
`Undefined variable $engineRawVersion`

Fix undefined variable $engineRawVersion

---

CHANGELOG.md
src/Image/Format.php
tests/tests/Filter/Advanced/BlackWhiteTest.php
tests/tests/Image/AbstractImageTest.php
tests/tests/Image/FormatTest.php
tests/tests/Issues/Issue131Test.php

I have discovered that $image->show() was setting invalid Content-Type header. "jpg" in case of "jpg" format instead of "image/jpg".
There seems to be an invalid argument order in the constructor call to Imagine\Image\Format.
The constructor signature is:
`private function __construct($id, $mimeType, $canonicalFileExtension, $alternativeIDs = array())`
While callers were clearly setting MIME type into 3. argument instead of second one.

Fix invalid format MIME type definition

---

src/Image/Point.php

remove deprecated message from php8.2
edit: i guest this PR related to #843 😳
`Deprecated: Implicit conversion from float 345.5 to int loses precision in ...\vendor\imagine\imagine\src\Gd\Image.php on line 191`
on https://github.com/php-imagine/Imagine/blob/6d5b83a403d17236ba3b7e52e3c2caf4e937d0f0/src/Gd/Image.php#L191
`imagecopymerge()` need `dst_x` and `dst_y` to be int.
but `$start->getX()` and `$start->getY()` could return float.

remove warning, Deprecated: Implicit conversion from float to int loses precision in PHP 8.2

---

src/Gd/Image.php
src/Gmagick/Image.php
tests/tests/Image/AbstractImageTest.php

Fixes #857 
The IMagick driver already supports the `webp_lossless` option, see https://github.com/php-imagine/Imagine/blob/922e0327a6b36d1da0acca69993ac85395adcea6/src/Imagick/Image.php#L829-L831
This pull request adds support for GD and GMagick too.

Add support for webp_lossless to GD and GMagick
