php-imagine/Imagine

- .gitattributes
Triming ~5Mb with composer --prefer-dist
> Ignore all test and documentation with the "export-ignore" attribute

- lib/Imagine/Imagick/Layers.php
changing animated gif delay/loop does not work
> fix-animated-gif

- README.md
How to install this package using the composer is added to the read me file.
> Composer installation instruction added.

- lib/Imagine/Image/AbstractImagine.php
- lib/Imagine/Image/Metadata/ExifMetadataReader.php
> Load exif metadata reader if available

- lib/Imagine/Image/Metadata/MetadataBag.php
> Add metadata getter

- .travis.yml
> Fix: Travis build configuration

- lib/Imagine/Imagick/Image.php
Not so nice but working fix for https://github.com/avalanche123/Imagine/issues/496
Does anyone else know a better solution?
The constants seem to be gone. I could not find new constants to use.
> Fix imagine7 constants

- .travis.yml
- composer.json
- tests/Imagine/Test/Draw/LinePlotterTest.php
- tests/Imagine/Test/Filter/Advanced/BorderTest.php
- tests/Imagine/Test/Filter/Advanced/GrayscaleTest.php
- tests/Imagine/Test/Filter/Chart/ChartConfigTest.php
- tests/Imagine/Test/Filter/FilterTestCase.php
- tests/Imagine/Test/Filter/ImagineAwareTest.php
- tests/Imagine/Test/Gd/ImagineTest.php
- tests/Imagine/Test/Gd/LayersTest.php
- tests/Imagine/Test/Gmagick/LayersTest.php
- tests/Imagine/Test/Image/Palette/AbstractPaletteTest.php
- tests/Imagine/Test/Imagick/ImageTest.php
- tests/Imagine/Test/Imagick/LayersTest.php
Obviously the test suite segfaults on PHP 5.3, will add a debug branch soon
> Fix test suite on Travis

- lib/Imagine/Gd/Image.php
Please reopen with a unit test
> Revert "Getting applyMask to work"

- lib/Imagine/Image/Box.php
Please - at least - document. I'd personaly use a factory shortcut like `Box::square`
> Revert "If box is a square, providing width is enough"

- lib/Imagine/Imagick/Image.php
> Revert "Fix Imagick "rotate" page alignment"

- README.md
I saw some headings weren't displaying correctly, and fixed them.
> Fix Markdown headings in README

- .travis.yml
This could fix random failures of tests that download images via HTTPS
> Update CA certificates

- lib/Imagine/Image/Metadata/ExifMetadataReader.php
- tests/Imagine/Test/Image/Metadata/ExifMetadataReaderTest.php
> Fix exif_read_data warning 'File not supported' - The Revenge

- lib/Imagine/Image/Metadata/AbstractMetadataReader.php
> Avoid accessing an undefined array index of result of stream_get_meta_data

- .appveyor/configure.ps1
It's better: PhpManager runs a series of system checks
> Use PhpManager to install Composer

- CHANGELOG.md
- lib/Imagine/Gd/Image.php
- lib/Imagine/Gd/Layers.php
- lib/Imagine/Gmagick/Image.php
- lib/Imagine/Gmagick/Layers.php
- lib/Imagine/Imagick/Image.php
- lib/Imagine/Imagick/Layers.php
- tests/Imagine/Test/Image/AbstractImageTest.php
> Fix image clonation

- CHANGELOG.md
- lib/Imagine/Factory/ClassFactory.php
- lib/Imagine/Factory/ClassFactoryAwareInterface.php
- lib/Imagine/Factory/ClassFactoryInterface.php
- lib/Imagine/Gd/Font.php
- lib/Imagine/Gd/Image.php
- lib/Imagine/Gd/Imagine.php
- lib/Imagine/Gd/Layers.php
- lib/Imagine/Gmagick/Font.php
- lib/Imagine/Gmagick/Image.php
- lib/Imagine/Gmagick/Imagine.php
- lib/Imagine/Gmagick/Layers.php
- lib/Imagine/Image/AbstractFont.php
- lib/Imagine/Image/AbstractImage.php
- lib/Imagine/Image/AbstractImagine.php
- lib/Imagine/Image/AbstractLayers.php
- lib/Imagine/Image/ImagineInterface.php
- lib/Imagine/Imagick/Font.php
- lib/Imagine/Imagick/Image.php
- lib/Imagine/Imagick/Imagine.php
- lib/Imagine/Imagick/Layers.php
- tests/Imagine/Test/Factory/AbstractClassFactoryTest.php
- tests/Imagine/Test/Gd/ClassFactoryTest.php
- tests/Imagine/Test/Gmagick/ClassFactoryTest.php
- tests/Imagine/Test/Imagick/ClassFactoryTest.php
> Implement customizable factory methods - V2

- CHANGELOG.md
- lib/Imagine/Image/Palette/RGB.php
- tests/Imagine/Test/Image/Palette/RGBTest.php
> Hotfix color gradients - Rebased

- tests/Imagine/Test/Constraint/AbstractIsImageEqualTest.php
- tests/Imagine/Test/Constraint/IsImageEqual.php
- tests/Imagine/Test/Gd/IsImageEqualTest.php
- tests/Imagine/Test/Gmagick/IsImageEqualTest.php
- tests/Imagine/Test/Imagick/IsImageEqualTest.php
- tests/bootstrap.php
The `IsImageEqual` constraint doesn't seem to work, I'll try to fix it.
> Fix IsImageEqual constraint

- tests/Imagine/Test/Constraint/IsBoxInRange.php
- tests/Imagine/Test/Constraint/IsBoxInRangeTest.php
- tests/Imagine/Test/Gd/ImagineTest.php
- tests/Imagine/Test/Gmagick/ImagineTest.php
- tests/Imagine/Test/Image/AbstractImagineTest.php
- tests/Imagine/Test/Imagick/ImagineTest.php
- tests/Imagine/Test/ImagineTestCase.php
I've seen slightly different values of the determined box, system-specific.
So, let's just check that the determined box is within a range of values.
> Let ImagineTest::testShouldDetermineFontSize() accept a range of values

- CHANGELOG.md
- src/Gd/Image.php
- src/Gmagick/Image.php
- src/Image/ManipulatorInterface.php
- src/Image/PointSigned.php
- src/Imagick/Image.php
- tests/Imagine/Test/Image/AbstractImageTest.php
> Don't force to paste images fully included in the destination image

- CHANGELOG.md
- src/Imagick/Image.php
- tests/Imagine/Test/Image/AbstractImageTest.php
> Fix Imagick save compression of PNG images

- CHANGELOG.md
- src/Gmagick/Image.php
- src/Image/Palette/CMYK.php
- src/Image/Palette/Grayscale.php
- src/Image/Palette/PaletteInterface.php
- src/Image/Palette/RGB.php
- src/Imagick/Image.php
- tests/Imagine/Test/Constraint/IsColorSimilar.php
It's often useful to know the max value that a color channel can accept
> Add getChannelsMaxValue to PaletteInterface

- .travis.yml
- .travis/autoupdate-api.sh
Let's update the API docs automatically when pushing to `develop`.
> Automatic generation of API docs

- src/Imagick/Imagine.php
> Don't run Imagine with ImageMagick 7.0.7-32

- CHANGELOG.md
- src/Image/AbstractImage.php
- src/Image/ManipulatorInterface.php
- tests/tests/Image/AbstractImageTest.php
> Add flag to thumbnail() to let it modify the image instance itself

- src/Image/Metadata/ExifMetadataReader.php
> Extract all EXIF metadata

- docs/usage/introduction.rst
Based on this merged pull-request https://github.com/avalanche123/Imagine/pull/504 , webp is now supported, so let's please show this in docs ;)
> Documenting the webp support

- src/Image/Box.php
- tests/tests/Image/BoxTest.php
> Fix passing big integers to box constructor

- CHANGELOG.md
- src/Gd/Image.php
- src/Gd/Imagine.php
- src/Image/Metadata/ExifMetadataReader.php
- src/Imagick/Image.php
- src/Imagick/Imagine.php
- src/Utils/ErrorHandling.php
> Centralize error handling functions, fix #715

- src/Gd/Image.php
Fix for #726 
JPEG images with jfif extensions would be handled by GD Image
> Handle jfif extension in gd image

- .php_cs.dist
Their fixer definitions change across different PHP-CS-Fixer versions
> Expand PHP-CS-Fixer sets

- src/Gmagick/Image.php
- src/Imagick/Image.php
- tests/tests/Image/AbstractImageTest.php
>  Fix converting of gif to jpg with imagick adapter - Take 2

- tests/tests/Draw/AbstractDrawerTest.php
See https://travis-ci.com/github/avalanche123/Imagine/jobs/427237250
> Be less picky in DrawerTest::testText

- src/Imagick/Imagine.php
- tests/tests/Image/AbstractLayersTest.php
Fixes a bug introduced in 9f32b46e3eec8f9d135e226cd3bbc2ff99971d8f
> Fix wrong load logic in Imagick

- README.md
Small Text Change
Maybe also remove the PHP Version here:
> Update README.md (min. PHP Version to 5.5)

- src/Gd/Layers.php
- src/Gmagick/Layers.php
- src/Image/Histogram/Bucket.php
- src/Imagick/Layers.php
> Add @return phpdoc to ReturnTypeWillChange methods

- src/Gmagick/Layers.php
- src/Imagick/Layers.php
- tests/tests/Gmagick/LayersTest.php
- tests/tests/Imagick/LayersTest.php
Hello ! 
Like Gif, Webp can be used as animated format 
https://developers.google.com/speed/webp/faq
Thanks a lot for your review
> Webp format should be animated
